title: Jonathan Berger
email: jonathanpberger+public@gmail.com
description: >-
  Jonathan Berger is a product designer and developer who loves people, 
  technology, and the intersection of the two.

# Default env - use production values since GitHub Pages always uses JEKYLL_ENV=production
baseurl: "/jpb.com"
url: "https://jonathanpberger.github.io"

# Environment-specific settings
development:
  baseurl: ""
  url: "https://localhost:4000"
staging:
  baseurl: "/jpb.com" # for GitHub Pages project site
  url: "https://jonathanpberger.github.io"
production:
  baseurl: "/jpb.com" # for GitHub Pages project site
  url: "https://jonathanpberger.github.io"

# These will be used when we move to custom domain
# production:
#   baseurl: ""
#   url: "https://jonathanpberger.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-redirect-from

# Preserve URLs
permalink: pretty

# Include these files/folders
include:
  - assets
  - _pages

# Exclude these files/folders
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .tool-versions
  - Rakefile
  - knowledge.md
  - public_folder
