title: Jonathan Berger
email: jonathanpberger+public@gmail.com
description: >-
  Jonathan Berger is a product designer and developer who loves people, 
  technology, and the intersection of the two.

# baseurl being overwritten in Rakefile for now :-/
baseurl: "/jpb.com"
url: "https://jonathanpberger.github.io"

# Production settings for custom domain
production:
  baseurl: ""
  url: "https://jonathanpberger.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-redirect-from

# Preserve URLs
permalink: pretty

# Include these files/folders
include:
  - assets
  - _pages

# Exclude these files/folders
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .tool-versions
  - Rakefile
  - knowledge.md
  - public_folder
