title: Jonathan Berger
email: jonathanpberger+public@gmail.com
description: >-
  Jonathan Berger is a product designer and developer who loves people, 
  technology, and the intersection of the two.
# URL configuration - uses environments to switch between local/staging/prod
baseurl: ""  # default for development
url: "http://localhost:4000"  # default for development

staging:
  baseurl: "/jpb.com"
  url: "https://jonathanpberger.github.io"

production:
  baseurl: ""
  url: "https://jonathanpberger.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-redirect-from

# Preserve URLs
permalink: pretty

# Redirects
redirect_from:
  /blog: "http://jonathanpberger.wordpress.com"
  /cal: "https://calendly.com/jonathanpberger"
  /calendar: "https://calendly.com/jonathanpberger"
  /calendly: "https://calendly.com/jonathanpberger"
  /cv: "/cv.pdf"
  /resume: "/cv.pdf"
  /resume.pdf: "/cv.pdf"

# Collections
collections:
  talks:
    output: true
    permalink: /talks/:path/

# Include these files/folders
include:
  - assets
  - _pages

# Exclude these files/folders
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .tool-versions
  - Rakefile
  - knowledge.md
  - public_folder
